export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//ATTRIBUTE actions
export const GET_ALL_ATTRIBUTES_SUCCESS = 'GET_ALL_ATTRIBUTES_SUCCESS';
export const GET_NEXT_PAGE_ATTRIBUTES_SUCCESS = 'GET_NEXT_PAGE_ATTRIBUTES_SUCCESS';
export const CREATE_ATTRIBUTE_SUCCESS = 'CREATE_ATTRIBUTE_SUCCESS';
export const UPDATE_ATTRIBUTE_SUCCESS = 'UPDATE_ATTRIBUTE_SUCCESS';
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS';
export const SET_TOTAL_NUMBER_OF_ATTRIBUTES = "SET_TOTAL_NUMBER_OF_ATTRIBUTES";
export const DECREMENT_TOTAL_NUMBER_OF_ATTRIBUTES = "DECREMENT_TOTAL_NUMBER_OF_ATTRIBUTES";
export const CHECKING_FOR_ATTRIBUTES = 'CHECKING_FOR_ATTRIBUTES';
export const CHECKING_FOR_ATTRIBUTES_SUCCESS = 'CHECKING_FOR_ATTRIBUTES_SUCCESS';
export const CHECKING_FOR_ATTRIBUTES_FAILURE = 'CHECKING_FOR_ATTRIBUTES_FAILURE';